#!/usr/env zsh

# general aliases
alias 1='cd -'
alias 2='git checkout -'
alias gs=''
alias p3='python3'
alias l='ls -l'
alias rg='rg -S'
alias fs='cd ~/scripts'

# pacman aliases
alias pss='pacman -Ss'
alias sps='sudo pacman -S'
alias syu='sudo pacman -Syu'

alias yss='yay -Ss'
alias ys='yay -S'

# fzf aliases (require the definition of fzz command in scripts)
alias nf='file=$(fzz) && nvim $file'
alias bf='file=$(fzz) && bat $file'
alias fcd='file=$(fd -td . | fzf) && cd $file'

# Git aliases
alias gp='git push'
alias gpu='git push -u origin'
alias gl='git pull'
alias gsi='git submodule init'
alias gss='git submodule sync'
alias gsu='git submodule update'
alias glsu='git pull && git submodule update'
alias gst='git status'
alias gsh='git stash'
alias gsp='git stash pop'
alias gsd='git stash drop'
alias gc='git commit --verbose'
alias gcm='git commit --verbose -m'
alias gco='git checkout'
alias gcom='git checkout master'
alias gcb='git branch -a --contains HEAD'
alias gadog='git log --graph --pretty=format:"%C(red)%h %C(yellow)%d %C(white)%s %C(green)%cr %C(bold blue)<%an>" --abbrev-commit'
alias gaa='git add --all'
alias gfa='git fetch --all'
alias gb='git branch'
alias grs='git reset'
alias gra='git restore :/'
alias grv='git remote -v'

# If eza exists replace ls with eza
if whence -p eza >/dev/null; then
  alias ls='eza --group-directories-first'
fi
